### ISSUE TITLE
domain docs.coralproject.net

### ISSUE THREAD

**Issue by gabelula** [coralproject/docs#9]
Get it for http://coral-docs.readthedocs.io/

**Comment by aiboyles** [comment]
This is kind of blocked right now.

Basically: we have docs.coralproject.net, but we can't get it to work as an HTTPS because we are using it with GitHub project pages, which do not support HTTPS.

We've tried using CloudFlare, but that doesn't work either (because it's a GitHub project page rather than a GitHub organization page).

For now, we are keeping the domain as http://docs.coralproject.net while we figure out what to do next. It may be that GitHub starts supporting HTTPS for project pages in future, but for now they have no timeline for when that might happen.

**Comment by losowsky** [comment]
Boo. We can't just wait and cross our fingers for that. Any other options? Hosting elsewhere?

**Comment by gabelula** [comment]
Can you check if this would work with heroku? 

https://devcenter.heroku.com/articles/ssl-endpoint#dns-and-domain-configuration

**Comment by aiboyles** [comment]
The domain now works. It uses CloudFlare.
